import AppKit
import ApplicationServices
import Carbon.HIToolbox
import VoicePartyCore

/// Puts text into whatever app has focus: pasteboard + synthetic ⌘V (works in native, Electron and
/// web apps), then restores the user's clipboard if nothing else has touched it since.
@MainActor
final class TextInserter {
    private static let markerType = NSPasteboard.PasteboardType("dev.voiceparty.inserted")
    /// nspasteboard.org conventions: clipboard managers skip these.
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]
    /// Password managers mark secrets this way; clipboard managers skip them.
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    enum Result { case pasted, copiedOnly }

    /// Called (on the main actor) when a paste was verified not to have landed.
    var onPasteFailed: ((String) -> Void)?
    private var pendingRestore: (task: Task<Void, Never>, saved: [[NSPasteboard.PasteboardType: Data]])?

    /// Pastes `text` and returns right away; the user's clipboard is restored in the background.
    /// When there's clearly no text field to paste into, the text is left on the clipboard instead.
    @discardableResult
    /// `html`: a rich version (real lists) offered alongside the plain text; apps that can't use it take the text.
    /// `conceal`: the text is a secret (dictated into a password field): mark it so clipboard managers skip it.
    func insert(_ text: String, html: String? = nil, conceal: Bool = false, restoreClipboard: Bool = true, pressEnter: Bool = false) async -> Result {
        let pasteboard = NSPasteboard.general
        // A restore still pending from the previous paste holds the user's real clipboard: keep that one.
        var saved: [[NSPasteboard.PasteboardType: Data]] = []
        if let pending = pendingRestore {
            pending.task.cancel()
            saved = pending.saved
            pendingRestore = nil
        } else if restoreClipboard {
            saved = Self.snapshot(pasteboard)
        }

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if let html { item.setString(html, forType: .html) }
        item.setData(Data(), forType: Self.markerType)
        for type in Self.transientTypes { item.setData(Data(), forType: type) }
        if conceal { item.setData(Data(), forType: Self.concealedType) }
        pasteboard.writeObjects([item])
        let ourChange = pasteboard.changeCount

        let focus = FocusProbe.decision()
        guard focus != .copyOnly else { return .copiedOnly }
        let before = FocusProbe.focusedValue()

        Self.postShortcut(key: Self.keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
        if pressEnter {
            try? await Task.sleep(for: .milliseconds(120))
            Self.postShortcut(key: CGKeyCode(kVK_Return), flags: [])
        }

        let restore = Task { [weak self] in
            // Verify the paste landed (only possible when the field exposes its text).
            try? await Task.sleep(for: .milliseconds(220))
            if let before, let after = FocusProbe.focusedValue(), after == before, !Task.isCancelled {
                self?.pendingRestore = nil
                self?.onPasteFailed?(text) // leave the text on the clipboard for the user
                return
            }
            // Give slow apps time to read the pasteboard before putting the old contents back.
            try? await Task.sleep(for: .milliseconds(600))
            guard !Task.isCancelled else { return }
            if restoreClipboard, pasteboard.changeCount == ourChange { Self.restore(saved, to: pasteboard) }
            self?.pendingRestore = nil
        }
        if restoreClipboard { pendingRestore = (restore, saved) }
        return .pasted
    }

    /// `keepOffHistory`: marked transient so clipboard managers skip it (it still pastes normally);
    /// `conceal` additionally marks it as a secret.
    func copy(_ text: String, html: String? = nil, keepOffHistory: Bool = TextInserter.defaultKeepOffHistory, conceal: Bool = false) {
        NSPasteboard.general.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if let html { item.setString(html, forType: .html) }
        if keepOffHistory || conceal { for type in Self.transientTypes { item.setData(Data(), forType: type) } }
        if conceal { item.setData(Data(), forType: Self.concealedType) }
        NSPasteboard.general.writeObjects([item])
    }

    /// Set from the history-retention setting ("never store" keeps copies out of clipboard managers).
    nonisolated(unsafe) static var defaultKeepOffHistory = false

    static func pressReturn() {
        postShortcut(key: CGKeyCode(kVK_Return), flags: [])
    }

    // MARK: - Helpers

    static func postShortcut(key: CGKeyCode, flags: CGEventFlags) {
        let source = CGEventSource(stateID: .combinedSessionState)
        for isDown in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: isDown) else { continue }
            event.flags = flags
            event.setIntegerValueField(.eventSourceUserData, value: syntheticEventMarker)
            event.post(tap: .cghidEventTap)
        }
    }

    /// Key code that types `character` in the current layout (so ⌘V works on Dvorak, AZERTY…).
    static func keyCode(for character: Character) -> CGKeyCode? {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let raw = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else { return nil }
        let data = Unmanaged<CFData>.fromOpaque(raw).takeUnretainedValue() as Data
        return data.withUnsafeBytes { bytes -> CGKeyCode? in
            guard let layout = bytes.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return nil }
            for code in 0..<128 {
                var dead: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                // With ⌘ held: layouts like "Dvorak – QWERTY ⌘" switch to QWERTY for shortcuts.
                let status = UCKeyTranslate(layout, UInt16(code), UInt16(kUCKeyActionDisplay), UInt32((cmdKey >> 8) & 0xFF), UInt32(LMGetKbdType()),
                                            OptionBits(kUCKeyTranslateNoDeadKeysBit), &dead, 4, &length, &chars)
                if status == noErr, length == 1, Character(UnicodeScalar(chars[0])!) == character { return CGKeyCode(code) }
            }
            return nil
        }
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { entry[type] = data }
            }
            return entry
        }
    }

    /// Puts the user's clipboard back — except a password manager's secret: re-copying it would reset the
    /// manager's auto-clear timer and keep the password around, so the clipboard is just cleared instead.
    /// Restored items are marked transient so clipboard managers don't record them a second time.
    private static func restore(_ items: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty, !items.contains(where: { $0[concealedType] != nil }) else { return }
        let restored = items.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry { item.setData(data, forType: type) }
            for type in transientTypes where entry[type] == nil { item.setData(Data(), forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

/// Asks Accessibility about the focused element.
enum FocusProbe {
    static func focusedElement() -> AXUIElement? {
        let system = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(system, 0.15)
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
              let focused, CFGetTypeID(focused) == AXUIElementGetTypeID() else { return nil }
        return (focused as! AXUIElement)
    }

    static func decision() -> FocusClassifier.Decision {
        guard let element = focusedElement() else { return .unknown }
        var role: CFTypeRef?
        AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &role)
        var settable: DarwinBoolean = false
        let settableKnown = AXUIElementIsAttributeSettable(element, kAXValueAttribute as CFString, &settable) == .success
        var editable: CFTypeRef?
        AXUIElementCopyAttributeValue(element, "AXEditable" as CFString, &editable)
        return FocusClassifier.decide(role: role as? String, valueSettable: settableKnown ? settable.boolValue : nil, editable: editable as? Bool)
    }

    /// The focused field's text, when it's readable and not huge (for paste verification).
    static func focusedValue() -> String? {
        guard let element = focusedElement() else { return nil }
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXValueAttribute as CFString, &value) == .success,
              let text = value as? String, text.utf16.count < 200_000 else { return nil }
        return text
    }
}
